const PRODUCTS_QUERY_KEY = ['PRODUCTS_QUERY_KEY']
const SIGNIN_QUERY_KEY = ['SIGNIN_QUERY_KEY']
const SIGNUP_QUERY_KEY = ['SIGNUP_QUERY_KEY']
const ITEM_QUERY_KEY = ['ITEM_QUERY_KEY']

export {
  PRODUCTS_QUERY_KEY,
  SIGNIN_QUERY_KEY,
  SIGNUP_QUERY_KEY,
  ITEM_QUERY_KEY,
}
